trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build Docker image
  inputs:
    containerRegistry: 'rcdocker'
    repository: 'sudhakarkethireddy/front-end'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 1.2
